### ISSUE TITLE
Character limit for Talkers/Lurkers

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#19]
Limit on the amount of characters for the Talkers and Lurkers list, should be shortened to fit on one line

**Comment by TheGreatCodeholio** [comment]
Will work on this.

**Comment by keirak420** [comment]
I have limited it to 20 characters, changed "days" to show "d" instead and those less than a day, I added a couple of spaces to help differentiate them from the ones over a day. It is currently on my development bot RBAP and will be pushed out for replication later today. Feel free to test it using rbap talkers/lurkers.

**Comment by keirak420** [comment]
done, closing
