### ISSUE TITLE
Subs with commands cannot be deleted

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#2]
Certain subs, mainly ones that have commands in them, cannot be deleted. Can we filter this, or change so it can be deleted or blocked?

**Comment by mzstalker** [comment]
Can be worked around (perhaps) by using "adam delete all subs" command.

**Comment by mzstalker** [comment]
There was an issue where Ralf's room could not delete a trigger than had a command in it. We tried different things with the “adam delete xx “ thinking maybe it was the way we were typing it. Eventually, we used adam delete all subs and redid it.

**Comment by mzstalker** [comment]
Issue may be in the trigger having a new line in the paragraph. Fixed, however, needs to be tested before closing ticket.

**Comment by keirak420** [comment]
"adam delete all subs" was added by Lucky and I have made revisions to prevent future issues. Triggers can only be single words, no longer than 20 characters. Here are some examples of valid options:

goodmorning
good.morning
good_morning
good_morning_1

These will not be accepted:
good morning
goodmorning 1

If you have any issues or questions, please let me know.
