### ISSUE TITLE
Adam not verifying in Group

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#20]
#adelaidegaynorthguys

Admin @sumfinnu

Admin not verifying members joining. Set up is checked to be correct, tried adding new members and different Adams. Will have to wait the 12 hours to see if captcha works for him. He said all of his rooms work except that room.

**Comment by mzstalker** [comment]
Went back to grab a screenshot, realized Adam is saying he can verify now, even though we just added that Adam
![image](https://user-images.githubusercontent.com/79489250/109577200-0f9e6580-7aaa-11eb-8f69-4db798a4f95b.jpeg)

Those are his settings.

**Comment by mzstalker** [comment]
After 12 hours, captcha still fails at new entry. Noob is also not working in said group.

**Comment by TheGreatCodeholio** [comment]
This seems to be a database issue. Possibly caused by old information from a banned Adam. I need group jid to check for entries.

**Comment by mzstalker** [comment]
I replaced and set up a new Adam last night. Waiting on the 12 hour mark to see if it works. Will close ticket if so. If not, will post his jid and group jid

**Comment by mzstalker** [comment]
Issues resolved
