### ISSUE TITLE
Adam not restoring in group chat

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#21]
Group jid This groups GID is: 1100234798126_g@groups.​kik.​com

@misterj928 person of contact

-Adam was not responding to admins other than his name

-Techs readded and tried different adams

-restore did not work

-database error would start, we would add a member, then would start again after some mins later

-default settings would return after each database error message

**Comment by keirak420** [comment]
User recreated their group and the problem went away. It was specific to that original group. I am unable to investigate the issue further as I am unable to replicate the issue. I am closing this issue as mute.

Keira
