### ISSUE TITLE
Adma sub 2 and 3 are both mixed mode

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#22]
Sub 3 needs to be Admin only for triggers ![image](https://user-images.githubusercontent.com/79489250/109868335-58762b80-7c1c-11eb-82c9-fd499da1e6a8.png)

**Comment by TheGreatCodeholio** [comment]
This was just a text issue. The mode was actually changing as it should, but reporting back it was in Mixed Mode
