### ISSUE TITLE
Adams default is not all identical

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#25]
Member complained that when setting up different Adams, the default was not all the same for each Adam. ![image](https://user-images.githubusercontent.com/79489250/110163813-6b683780-7da5-11eb-8c7b-bcb19bedcc70.png)![image](https://user-images.githubusercontent.com/79489250/110163836-728f4580-7da5-11eb-81df-7f8b406d2a11.png)![image](https://user-images.githubusercontent.com/79489250/110163851-78852680-7da5-11eb-89dc-15923a01a6ba.jpeg)

**Comment by TheGreatCodeholio** [comment]
All of Adam's defaults are the same. In this case I believe it was due to the database not being deleted when Adam was removed.
