### ISSUE TITLE
Adam is ignoring a member

### ISSUE THREAD

**Issue by mzstalker** [TheGreatCodeholio/adam-kikbot#8]
Adam wont respond to member with the gid bcaenzenij6bcxbtuxnyzd5jm5nzmlezmabbas2gp6rsodsmqdyq_a@talk.​kik.​com

This is true for all 11 Adam bots. Tested on many user alt profiles, added and readded members and replaced Adam several times. 

Group is a public room.

Troubleshooted, but nothing worked.

**Comment by keirak420** [comment]
Would you please provide me some way to contact the user, either their username or a name and group that they are located at so I can do further troubleshooting with them?

**Comment by mzstalker** [comment]
Its Papi , his user name is @papi_ahles , although all his alts are being ignored by Adam. I reached out to him to see if this is still a current issue, will update once he replies

**Comment by mzstalker** [comment]
Troubleshooting with member, in room #over40owners . Adam now responds to some commands, but will not set verification for him. Adam sets both sub 2 and 3 as mixed mode. ![image](https://user-images.githubusercontent.com/79489250/109575586-f516bd00-7aa6-11eb-898c-00997f7b04b3.png)![image](https://user-images.githubusercontent.com/79489250/109575605-0069e880-7aa7-11eb-82d6-15c0a970571c.png)

Responds the same for me as well.

**Comment by mzstalker** [comment]
Restore is also not working for said member![image](https://user-images.githubusercontent.com/79489250/109577400-4eccb680-7aaa-11eb-9a02-9751eb11994d.jpeg)

**Comment by mzstalker** [comment]
Wants to be labeled as a super user? Is that a thing![image](https://user-images.githubusercontent.com/79489250/109702387-057f7400-7b49-11eb-8007-dfd49923eea2.png)

**Comment by mzstalker** [comment]
When restoring adam, goes back to default and acts as if adam hasnt been in the room before. Eve kik jail restores so captcha is not shown
